# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20171225_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstockitem',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalstockitem',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
